"""新增平台仅需实现此接口，并在注册表添加工厂。"""

from typing import Callable, Protocol
from app.core.models import ChatMessage, ChatSnapshot


class AdapterError(RuntimeError):
    pass


class BaseChatAdapter(Protocol):
    def get_platform_name(self) -> str: ...
    def detect_window(self) -> dict: ...
    def inspect(self) -> ChatSnapshot: ...
    def get_current_contact(self) -> str: ...
    def get_messages(self) -> tuple[ChatMessage, ...]: ...
    def get_new_messages(self) -> tuple[ChatMessage, ...]: ...
    def focus_input(self, expected: ChatSnapshot, check: Callable[[], None]) -> None: ...
    def fill_message(self, text: str, expected: ChatSnapshot, check: Callable[[], None]) -> str: ...
    def send_message(self, text: str, expected: ChatSnapshot, check: Callable[[], None]) -> str: ...
